- name: install {{ payload }}
  yum:
    name: "{{ payload }}"
    state: latest

- name: enable {payload} at boot time
  service:
    name: "{{ payload }}"
    enabled: yes

- name: create HAproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: start {{ payload }}
  service: 
    name: "{{ payload }}"
    state: restarted

