---
#- name: Configure 3teir on AWS
#  hosts: jumpbox
#  roles:
#   - { role: ../3tiers/roles/osp.facts }
#  tags:
#    - osp.facts

#- name: Setup RedHat Repositories
#  hosts: all
#  roles:
#   - { role: ../3tiers/roles/repo-config }
#  tags:
#    - setup-repos

- name: Setup HAProxy
  hosts: frontends
  roles:
   - { role: ../3tiers/roles/lb-tier }
  tags:
    - setup-haproxy

- name: Setup application1 
  hosts: apps
  roles:
   - { role: ../3tiers/roles/apptier }

- name: Setup postgresql
  hosts: appdbs
  roles:
   - { role: ../3tiers/roles/geerlingguy.postgresql }
  tags:
    - setup-postgresql
