- hosts: jumpbox
  gather_facts: false
  roles:
    - {name: osp-facts, when: ansible_product_name ==  'OpenStack Compute'}

- name: setup LB tier
  hosts: frontends
  become: yes
  roles:
    - base-config
    - lb-tier
  
- name: setup app tier
  hosts: apps
  become: yes
  roles:
    - base-config
    - app-tier

- name: setup postgresql
  hosts: appdbs
  become: yes
  roles:
    - base-config
    - geerlingguy.postgresql
